[local]
localhost

[mongodb]
mongodb.piridishop.shop

[redis]
redis.piridishop.shop

[mysql]
mysql.piridishop.shop

[rabbitmq]
rabbitmq.piridishop.shop

[catalogue]
catalogue.piridishop.shop

[user]
user.piridishop.shop

[cart]
cart.piridishop.shop

[shipping]
172.31.5.185 

[payment]
payment.piridishop.shop

[frontend]
172.31.2.65

